In [1]:
# Import essential libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import math as math
%matplotlib inline
sb.set()
plt.style.use('fivethirtyeight')

In [2]:
games = pd.read_pickle('datasets/cleaned_steam_games.pkl')
games

,name,all_reviews,release_date,developer,publisher,genre,mature_content,original_price,discount_price,genre_Action,...,languages_Simplified Chinese,languages_Slovakian,languages_Spanish - Latin America,languages_Spanish - Spain,languages_Swedish,languages_Thai,languages_Traditional Chinese,languages_Turkish,languages_Ukrainian,languages_Vietnamese
0,DOOM,92,2016-05-12,id Software,"Bethesda Softworks,Bethesda Softworks",{Action},False,19.99,14.99,1,...,0,0,0,1,0,0,1,0,0,0
1,PLAYERUNKNOWN'S BATTLEGROUNDS,49,2017-12-21,PUBG Corporation,"PUBG Corporation,PUBG Corporation","{Adventure, Action, Massively Multiplayer}",True,29.99,NaN,1,...,1,0,0,1,0,1,1,1,1,0
2,BATTLETECH,71,2018-04-24,Harebrained Schemes,"Paradox Interactive,Paradox Interactive","{Adventure, Action, Strategy}",False,39.99,NaN,1,...,0,0,0,0,0,0,0,0,0,0
3,DayZ,61,2018-12-13,Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","{Adventure, Action, Massively Multiplayer}",False,44.99,NaN,1,...,1,0,0,1,0,0,1,0,0,0
4,EVE Online,74,2003-05-06,CCP,"CCP,CCP","{Action, Massively Multiplayer, Strategy, RPG}",False,0.0,NaN,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40481,雨上がりのハナビィ Ameagari no Hanaby,100,2018-09-22,Enigmatic Network,"Enigmatic Network,Enigmatic Network","{Adventure, Action, Casual}",True,13.99,NaN,1,...,0,0,0,0,0,0,0,0,0,0
40524,Lil Big Invasion,100,2016-08-04,Andreas Britten,"Andreas Britten,Andreas Britten","{Adventure, Action}",False,2.99,NaN,1,...,0,0,0,0,0,0,0,0,0,0
40598,Detached: Non-VR Edition,78,2018-07-24,Anshar Studios,"Anshar Studios,Anshar Studios",{Simulation},False,14.99,NaN,0,...,1,0,0,0,0,0,0,0,0,0
40611,A Room Beyond,90,2017-06-13,René Bühling,"René Bühling,René Bühling",{Adventure},False,7.99,NaN,0,...,0,0,0,1,0,0,0,0,0,0
40811,Nanoui,28,2018-03-21,Phoesion,"Phoesion,Phoesion","{Adventure, Action, Casual, RPG}",False,6.99,NaN,1,...,0,0,0,0,0,0,0,0,0,0

## Dealing with NULL values

In [3]:
# Data resampling
games['all_reviews'] = pd.to_numeric(games['all_reviews'])
games['original_price'] = pd.to_numeric(games['original_price'])
games['discount_price'] = pd.to_numeric(games['discount_price'])

games['original_price'] = games['original_price'].fillna(6.99)
games['discount_price'] = games['discount_price'].fillna(games['original_price'])
games = games[(games['original_price'] >= games['discount_price'])]

games['discount_percentage'] = (games['original_price'] - games['discount_price'])/games['original_price'] * 100
games['discount_percentage'] = games['discount_percentage'].fillna(0)

C:\Users\User\AppData\Local\Temp\ipykernel_20804\2830625690.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['discount_percentage'] = (games['original_price'] - games['discount_price'])/games['original_price'] * 100
C:\Users\User\AppData\Local\Temp\ipykernel_20804\2830625690.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['discount_percentage'] = games['discount_percentage'].fillna(0)

In [4]:
# Replace NaN values in column 'B' with the mode
games['publisher'] = games['publisher'].fillna(games['publisher'].mode().iloc[0])
games['developer'] = games['developer'].fillna(games['publisher'])

C:\Users\User\AppData\Local\Temp\ipykernel_20804\4054960629.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['publisher'] = games['publisher'].fillna(games['publisher'].mode().iloc[0])
C:\Users\User\AppData\Local\Temp\ipykernel_20804\4054960629.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['developer'] = games['developer'].fillna(games['publisher'])

Response variable

In [23]:
games['all_reviews'] = pd.to_numeric(games['all_reviews'])
games['status'] = np.where(games['all_reviews'] >= 70, 'good', 'bad')

C:\Users\User\AppData\Local\Temp\ipykernel_20804\2260643566.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['all_reviews'] = pd.to_numeric(games['all_reviews'])
C:\Users\User\AppData\Local\Temp\ipykernel_20804\2260643566.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['status'] = np.where(games['all_reviews'] >= 70, 'good', 'bad')

# Resampling data

## Dealing with categorical variables

Now, we are going to change our categorical data into numerical form by `OneHotEncoding` because our Machine Learning Models can only deal with numerical data.

`Linear Regression` and `Random Forest Regression `in `sklearn` do not handle categorical variables directly as a part of the current implementation. Thus, we will need to encode the levels of a categorical variable as integers. One way to encode nominal (unordered) categorical variables by integers is `OneHotEncoding`.

### One Hot Encoding

In [6]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

# OneHotEncoding of categorical predictors (not the response)
games_cat = games[['publisher', 'developer']]
ohe.fit(games_cat)
games_cat_ohe = pd.DataFrame(ohe.transform(games_cat).toarray(), 
                                  columns=ohe.get_feature_names_out(games_cat.columns))

# Check the encoded variables
games_cat_ohe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11355 entries, 0 to 11354
Columns: 13602 entries, publisher_ ,  to developer_黄昏フロンティア
dtypes: float64(13602)
memory usage: 1.2 GB

In [7]:
games_cat_ohe.head()

,"publisher_ ,","publisher_ AYE Technology, AYE Technology","publisher_ Aerosoft GmbH, Aerosoft GmbH","publisher_ Casual Trash Studios, Casual Trash Studios","publisher_ Expect Studio , Expect Studio","publisher_ Fazan, Fazan","publisher_ FobTi interactive, FobTi interactive","publisher_ GrabTheGames, GrabTheGames","publisher_ GungHo Online Entertainment America, Inc.\t, GungHo Online Entertainment America, Inc.\t","publisher_ Imbanova Entertainment Inc., Imbanova Entertainment Inc.",...,developer_边境游戏工作室,developer_铸城工作室,developer_阿正不经,developer_阿津,developer_阿达游戏,developer_陌上科技,developer_雷武游戏,"developer_風林火山工作室,東木酋長",developer_高考恋爱委员会,developer_黄昏フロンティア
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Since there are too many number of columns created from OneHotEncoding, it will create a substantial amount `noise` to distrub the Machine Learning process, hence we have to cluster them into some clusters to reduce to number of columns.

### K-means

In [8]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

alldeveloper = games_cat_ohe.filter(regex='^developer_')
allpublisher = games_cat_ohe.filter(regex='^publisher_')

def kMeansFunc(data, n_clusters):
    # Load the data

    # Standardize the data
    scaler = StandardScaler()
    data_std = scaler.fit_transform(data)

    # Create a k-means object with 3 clusters
    kmeans = KMeans(n_clusters= n_clusters, random_state=42)

    # Fit the k-means object to the data
    kmeans.fit(data_std)

    # Get the cluster labels
    labels = kmeans.labels_

    # Add the cluster labels to the original data
    data['Cluster'] = labels

    # Print the number of data points in each cluster
    print(data['Cluster'].value_counts())

In [9]:
kMeansFunc(alldeveloper, 15)

8     11297
2        25
6         5
13        5
9         3
11        3
4         3
14        3
1         2
5         2
12        2
0         2
7         1
10        1
3         1
Name: Cluster, dtype: int64

C:\Users\User\AppData\Local\Temp\ipykernel_20804\2443899734.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Cluster'] = labels

In [10]:
kMeansFunc(allpublisher, 10)

9    11252
5       45
2       35
3       10
8        5
4        3
6        2
1        1
7        1
0        1
Name: Cluster, dtype: int64

C:\Users\User\AppData\Local\Temp\ipykernel_20804\2443899734.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Cluster'] = labels

Since K-Means clustering gives such a unevenly distribution of data with most of the data having the same value, it is not meaningful at all by using K-Means clustering. Instead, we come out with another clustering method called Principal Component Analysis (PCA). By using PCA, we can achieve dimensionality reduction, information compression, data de-noising, and many more.

 ### Principal Component Analysis (PCA)

In [11]:
# Import PCA
from sklearn.decomposition import PCA

# PCA for publisher
X = allpublisher

# Create a PCA object with 5 components
pca = PCA(n_components=5)

# Fit the PCA model to the data
pca.fit(X)

# Transform the data using the PCA model
X_pca = pca.transform(X)

# Create a new DataFrame with the transformed data
publisher_pca = pd.DataFrame(X_pca, columns=["Publisher_PC1", "Publisher_PC2", "Publisher_PC3", "Publisher_PC4", "Publisher_PC5"])


publisher_pca

,Publisher_PC1,Publisher_PC2,Publisher_PC3,Publisher_PC4,Publisher_PC5
0,-0.047265,-0.049798,-0.016603,-0.007283,-0.029931
1,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810
2,-0.047440,-0.051125,-0.020750,-0.009496,-0.040103
3,-0.046718,-0.046000,-0.010165,-0.004037,-0.016567
4,-0.046427,-0.044171,-0.008393,-0.003269,-0.013336
...,...,...,...,...,...
11350,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810
11351,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810
11352,-0.046381,-0.043896,-0.008169,-0.003174,-0.012938
11353,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810
11354,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810

In [14]:
publisher_pca.describe()

,Publisher_PC1,Publisher_PC2,Publisher_PC3,Publisher_PC4,Publisher_PC5
count,1.135500e+04,1.135500e+04,1.135500e+04,1.135500e+04,1.135500e+04
mean,1.496956e-16,-8.810892e-16,9.441326e-17,1.239025e-17,-6.482610e-17
std,5.182136e-01,2.062329e-01,1.002328e-01,9.598859e-02,9.498381e-02
min,-5.555106e-02,-5.737781e-02,-1.009149e-01,-5.318676e-01,-5.319326e-02
25%,-4.653357e-02,-4.445021e-02,-8.630859e-03,-3.336204e-03,-1.347405e-02
50%,-4.638086e-02,-4.389563e-02,-8.168599e-03,-3.143697e-03,-1.281008e-02
75%,-4.636564e-02,-4.380455e-02,-8.096331e-03,-3.143697e-03,-1.281008e-02
max,8.909369e+00,9.555654e-01,9.834452e-01,8.447602e-01,8.303740e-01

In [12]:
# PCA for developer

X = alldeveloper

# Create a PCA object with 5 components
pca = PCA(n_components=5)

# Fit the PCA model to the data
pca.fit(X)

# Transform the data using the PCA model
X_pca = pca.transform(X)

# Create a new DataFrame with the transformed data
developer_pca = pd.DataFrame(X_pca, columns=["Developer_PC1", "Developer_PC2", "Developer_PC3", "Developer_PC4", "Developer_PC5"])

developer_pca

,Developer_PC1,Developer_PC2,Developer_PC3,Developer_PC4,Developer_PC5
0,-0.013388,-0.008313,0.000069,-0.009827,-0.006300
1,-0.013233,-0.006333,0.000001,-0.006472,-0.003492
2,-0.013267,-0.006687,0.000002,-0.006995,-0.003871
3,-0.013388,-0.008316,0.000172,-0.009881,-0.007579
4,-0.013267,-0.006687,0.000002,-0.006995,-0.003871
...,...,...,...,...,...
11350,-0.013233,-0.006333,0.000001,-0.006472,-0.003492
11351,-0.013233,-0.006333,0.000001,-0.006472,-0.003492
11352,-0.013241,-0.006418,0.000001,-0.006595,-0.003580
11353,-0.013233,-0.006333,0.000001,-0.006472,-0.003492
11354,-0.013233,-0.006333,0.000001,-0.006472,-0.003492

In [15]:
developer_pca.describe()

,Developer_PC1,Developer_PC2,Developer_PC3,Developer_PC4,Developer_PC5
count,1.135500e+04,1.135500e+04,1.135500e+04,1.135500e+04,1.135500e+04
mean,-5.514419e-17,5.565842e-17,5.276044e-18,-1.883905e-18,-2.734500e-18
std,3.695921e-01,8.209349e-02,6.959961e-02,6.928597e-02,6.071661e-02
min,-5.993848e+00,-2.222593e-02,-7.070895e-01,-2.768870e-02,-1.475638e-02
25%,-1.325820e-02,-6.505348e-03,1.361623e-06,-6.723062e-03,-3.671934e-03
50%,-1.323254e-02,-6.333064e-03,1.361623e-06,-6.471715e-03,-3.492338e-03
75%,-1.323254e-02,-6.333064e-03,1.491035e-06,-6.471715e-03,-3.492338e-03
max,7.955742e+00,9.932598e-01,7.071236e-01,7.000490e-01,9.958956e-01

In [16]:
# Concatenate developer pca and publisher pca
games_pca = pd.concat([developer_pca, publisher_pca], axis = 1) # PCA of publisher and developer

# Reset index of both pca
games_pca.set_index(games.index, inplace=True)

In [21]:
# Combining Numeric features with the OHE Categorical features
games_num = games[['original_price','discount_price', 'discount_percentage']] 
games_res = games[['status']]
games_ohe = games.filter(regex='^genre_') # consists of all genre

games_train = pd.concat([games_num, games_ohe, games_pca, games_res], 
                           sort = False, axis = 1).reindex(index=games_num.index)

games_train

,original_price,discount_price,discount_percentage,genre_Action,genre_Adventure,genre_Casual,genre_Massively Multiplayer,genre_RPG,genre_Racing,genre_Simulation,...,Developer_PC2,Developer_PC3,Developer_PC4,Developer_PC5,Publisher_PC1,Publisher_PC2,Publisher_PC3,Publisher_PC4,Publisher_PC5,status
0,19.99,14.99,25.012506,1,0,0,0,0,0,0,...,-0.008313,0.000069,-0.009827,-0.006300,-0.047265,-0.049798,-0.016603,-0.007283,-0.029931,good
1,29.99,29.99,0.000000,1,1,0,1,0,0,0,...,-0.006333,0.000001,-0.006472,-0.003492,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810,bad
2,39.99,39.99,0.000000,1,1,0,0,0,0,0,...,-0.006687,0.000002,-0.006995,-0.003871,-0.047440,-0.051125,-0.020750,-0.009496,-0.040103,good
3,44.99,44.99,0.000000,1,1,0,1,0,0,0,...,-0.008316,0.000172,-0.009881,-0.007579,-0.046718,-0.046000,-0.010165,-0.004037,-0.016567,bad
4,0.00,0.00,0.000000,1,0,0,1,1,0,0,...,-0.006687,0.000002,-0.006995,-0.003871,-0.046427,-0.044171,-0.008393,-0.003269,-0.013336,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40481,13.99,13.99,0.000000,1,1,1,0,0,0,0,...,-0.006333,0.000001,-0.006472,-0.003492,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810,good
40524,2.99,2.99,0.000000,1,1,0,0,0,0,0,...,-0.006333,0.000001,-0.006472,-0.003492,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810,good
40598,14.99,14.99,0.000000,0,0,0,0,0,0,1,...,-0.006418,0.000001,-0.006595,-0.003580,-0.046381,-0.043896,-0.008169,-0.003174,-0.012938,good
40611,7.99,7.99,0.000000,0,1,0,0,0,0,0,...,-0.006333,0.000001,-0.006472,-0.003492,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810,good
40811,6.99,6.99,0.000000,1,1,1,0,1,0,0,...,-0.006333,0.000001,-0.006472,-0.003492,-0.046366,-0.043805,-0.008096,-0.003144,-0.012810,bad

In [22]:
games_train.to_csv('games-train.csv')